name:                chapter8
version:             0.1.0
github:              "frankhjung/chapter8"
license:             BSD3
author:              "Frank H Jung"
maintainer:          "frankhjung@linux.com"
copyright:           "Copyright © 2021 Frank H Jung"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            education

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: See <https://github.com/frankhjung/haskell-udemy#README>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  chapter8:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N1
    dependencies:
      - chapter8

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N1
    dependencies:
      - chapter8
